name: Build and Release

env:
  APP_NAME: GreedySnake
  PYTHON_VERSION: '3.9'
  BUILD_DIR: dist
  ASSET_DIR: assets

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame
        pip install Pillow
        pip install customtkinter
        pip install pywinstyles
        pip install pyinstaller
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm `
          --onefile `
          --windowed `
          --name "${{ env.APP_NAME }}" `
          --icon "${{ env.ASSET_DIR }}/images/snake_icon.ico" `
          --add-data "${{ env.ASSET_DIR }};${{ env.ASSET_DIR }}" `
          --hidden-import "pygame" `
          --hidden-import "pygame.mixer" `
          --hidden-import "pygame.display" `
          --hidden-import "customtkinter" `
          --clean `
          main.py
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/GreedySnake.exe
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
        body: |
          ## 贪吃蛇游戏 ${{ github.ref_name }} 版本发布
          
          ### 系统要求
          - Windows 7/8/10/11
          - 显示器分辨率 1280x720 或更高
          
          ### 安装说明
          1. 下载 GreedySnake.exe
          2. 双击运行即可开始游戏
          
          ### 游戏说明
          - 方向键控制蛇的移动
          - SPACE/P 暂停游戏
          - SPACE/P 继续游戏
          - R 重新开始游戏
          - B 返回
          ### 版本特性
          ${{ github.event.head_commit.message }}
          
          ### 已知问题
          如遇到问题，请在 Issues 中反馈。
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}